name: Alex Creates
favicon: null
layout_spectrum: 0.2517760854680091
typography_spectrum: 0.42784
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9039607469458133
  lightness: 0.28831946407444775
  saturation: 0.5648929181043059
  rhythmicContrast: 0.8724071304313838
purpose: []
